version: '3'
services:
  database:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
     #création d'une nouvelle base de données
      MONGO_INITDB_DATABASE: realestate
    volumes:
      # Ajout db-init.js dans le Mongo DB container pour initialiser la base de données
      - ./db-init.js:/docker-entrypoint-initdb.d/init.js:ro
    ports:
      - '27017-27019:27017-27019'
  web:
    build: .
    image: realestate-angular
    environment:
    # Utiliser le username et mot de passe trouvé dans db-init.js à la place du root username
      MONGODB_URI: mongodb://user:secretPassword@database/realestate
    depends_on:
      - database
    ports:
      - 8082:5000